tasks:
  - init: |
      docker run -d -p 8888:8888 -v /workspace:/config/workspace ghcr.io/lescai-teaching/rstudio-bio-gitpod:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    name: JupyterLab
    onOpen: open-browser
  - port: 8787
    name: RStudio
    onOpen: open-browser
